// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOMiixAu3xKVhSDfs1u7pryt5NgLC1qM',
    appId: '1:1037096653732:web:15680756f8f8af7ce26731',
    messagingSenderId: '1037096653732',
    projectId: 'flutter-crud-app-00',
    authDomain: 'flutter-crud-app-00.firebaseapp.com',
    storageBucket: 'flutter-crud-app-00.firebasestorage.app',
    measurementId: 'G-ZJ6LTQHZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClYFYaAOCZ8HmvcmbxprilFhBrFRwDmi0',
    appId: '1:1037096653732:android:bb1fcdb945a94943e26731',
    messagingSenderId: '1037096653732',
    projectId: 'flutter-crud-app-00',
    storageBucket: 'flutter-crud-app-00.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOMiixAu3xKVhSDfs1u7pryt5NgLC1qM',
    appId: '1:1037096653732:web:d119edcccc4f8e64e26731',
    messagingSenderId: '1037096653732',
    projectId: 'flutter-crud-app-00',
    authDomain: 'flutter-crud-app-00.firebaseapp.com',
    storageBucket: 'flutter-crud-app-00.firebasestorage.app',
    measurementId: 'G-PTXETJBHM7',
  );
}
